### ISSUE TITLE
[ADSR] Update encounter eligibility for Baseline encounter

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/Adolescent-Sewa-Rural#118] opened 2024-07-24 04:04 UTC
### Motive
Currently, due to some bug in the scripts that we ran, there are scenarios where individuals have there Baseline 2024 cancelled, now this is blocking the work on ground.

### Tech tasks 

To solve this we need to make an unplanned Baseline available for such cases, so update the encounter eligibilty check accordingly -

- [x] Fetch Baseline non cancelled encounters
- [x] It can be scheduled/completed but not cancelled ones for the current year (fetch year from today's date)
- [x] If there exists any one such visit then Hide the unplanned visit
- [x] Also, confirm that there is no unplanned visits available for exit cases
- [x] From May 15th onwards, this rule should run for the current year

- [x] **Make sure any visit scheduling doesn't break after completion of an Unplanned Baseline**

**Comment by Dinesh2019** [comment] 2024-07-25 05:17
@adamsanadi6 @nupoorkhandelwal need clarification on below points.
- [x] Scenario 1: if we completed the endline as dropped out then no visit gets scheduled but we can do the unplanned visit of baseline do we need to restrict that. **No it shouldn't if the visit scheduling requirement is such** **We will have to fix this**
- [x] Scenario 2: if the endline is scheduled but not completed, the user can also do the unplanned baseline visit. (which will lead to change or update or duplicate of encounters).**No it shouldn't**
- [x] Scenario 3 : the baseline is scheduled but also can able to see the unplanned visit of baseline. **No it shouldn't**

**Comment by Dinesh2019** [comment] 2024-07-25 10:12
Refre video for QA : 

[Click here for video](https://drive.google.com/file/d/1o2-Q88W3TV9CjrvuiMV3mdFdw2ZeyeM-/view?usp=drive_link)

**Closed as completed** 2024-08-01 06:45 UTC
